### ISSUE TITLE
Volcano dies when you attempt to send ffmpeg way too quickly

### ISSUE THREAD

**Issue by CheesyZaem** [AmandaDiscord/Volcano#7]
If you attempt to send ffmpeg twice in a row when ffmpeg is still not done processing the previous request, it will crash immediately... (sorry but i dont really know whats really happening so. here is the error i received)

```node:internal/event_target:641
  process.nextTick(() => { throw err; });
                            ^
 The "listener" argument must be of type function. Received undefined
     at checkListener (node:events:131:3)
     at AudioPlayer.removeListener (node:events:562:7)
     at Queue._applyPlayerEvents (/app/dist/worker.js:143:17)
     at Queue.play (/app/dist/worker.js:310:14)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
 Emitted 'error' event on Worker instance at:
     at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
     at Worker.[kOnMessage] (node:internal/worker:309:37)
     at MessagePort.<anonymous> (node:internal/worker:210:57)
     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:461:20)
     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
   code: 'ERR_INVALID_ARG_TYPE'
 }
```

**Comment by PapiOphidian** [comment]
Thank you for your report. I'll be pushing an update fixing this as soon as possible
